<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="ieee_robot">
  <xacro:property name="width" value="0.269875" />
  <xacro:property name="length" value="0.23495" />
  <material name="blue">
    <color rgba="0 0 0.8 1"/>
  </material>

  <material name="white">
    <color rgba="1 1 1 1"/>
  </material>

  <link name="base_link">
    <visual>
      <origin xyz="${length/2 -0.01525722} ${width/2 -0.05384791} 0.0" rpy="0 0 ${-pi/2}" />
      <geometry>
        <mesh filename="file://ROOT.stl"/>
        <box size="0.23495 0.269875 0.293653"/>
      </geometry>
      <material name="blue"/>
    </visual>
  </link>

  <link name="imu_link"/>
  <link name="camera_link"/>
  <link name="camera_link_optical"/>

  <joint name="base_imu" type="fixed">
    <parent link="base_link"/>
    <child link="imu_link"/>
    <origin xyz="-0.04281711 -0.12469021 0.21492789" rpy="${pi/2} ${-pi/2} 0.0"/>
  </joint>

  <joint name="base_camera" type="fixed">
    <parent link="base_link"/>
    <child link="camera_link"/>
    <origin xyz="0.11784511 0.0 0.09754467"/>
  </joint>

  <joint name="camera_optical_joint" type="fixed">
      <parent link="camera_link"/>
      <child link="camera_link_optical"/>
      <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
    </joint>
</robot>